# description of the site (will be placed in meta)
description = "치지레이지 리뷰 모음. The reviews of CHEESYLAZY"
# use bundled js and css
# * if you want to build the js and css from scratch, set this to false and run `npm install` and `npm run build`
# * tldr: set this to false if you want to develop and edit the js and css
bundled = false

# whether to use favicon resource links
# generate these with https://realfavicongenerator.net
favicon = true
# modern SVG favicon to use in place of older style .png and .ico files
svgFavicon = "/dot.svg"
# fallback png favicon for unsupported browsers
svgFaviconFallback = "/dot.png"

# resize options for dynamic resolution, please refer to https://gohugo.io/content-management/image-processing/#image-processing-options
loResOpt = "800x webp Lanczos q60"
hiResOpt = "2500x webp Lanczos q75"

# page config
[page]
# unified alt text for all images in the page
unifiedAlt = ''

# no cookie mode
No_cookie = true
# respect the do not track setting of the browser
Do_not_track = true
# token(optional), more info on https://splitbee.io/docs/embed-the-script
data_token = ""
